redis:
  image: redis:3.2-alpine
  ports:
    - 6385:6379
  container_name: script-redis

monitor:
  image: redis:3.2-alpine
  links:
    - redis
  entrypoint: "/bin/sh"
  command: >
    "-c" "redis-cli -h script-redis -p 6379 monitor"
